import type { Options as SanitizeOptions } from "rehype-sanitize";
import { defaultSchema } from "rehype-sanitize";

const POLICY: SanitizeOptions = {
  ...defaultSchema,
  tagNames: [
    "a",
    "abbr",
    "blockquote",
    "br",
    "code",
    "div",
    "em",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "kbd",
    "li",
    "mark",
    "ol",
    "p",
    "pre",
    "s",
    "span",
    "strong",
    "sup",
    "sub",
    "table",
    "tbody",
    "thead",
    "tfoot",
    "tr",
    "th",
    "td",
    "ul",
    "nav",
    "section",
  ],
  attributes: {
    a: ["href", "title", "target", "rel", "className"],
    code: ["className"],
    span: ["className"],
    div: ["className"],
    pre: ["className"],
    ol: ["className"],
    ul: ["className"],
    li: ["className"],
    table: ["className"],
    thead: ["className"],
    tbody: ["className"],
    tfoot: ["className"],
    tr: ["className"],
    th: ["className"],
    td: ["className"],
    nav: ["className"],
    section: ["className"],
    h1: ["id", "className"],
    h2: ["id", "className"],
    h3: ["id", "className"],
    h4: ["id", "className"],
    h5: ["id", "className"],
    h6: ["id", "className"],
  },
  protocols: {
    href: ["http", "https", "mailto", "tel", "sms", "ftp", "gopher", "irc", "ircs"],
  },
};

export default POLICY;
